### ISSUE TITLE
KanBan Board

### ISSUE THREAD

**Issue by Farida-Hamid** [Farida-Hamid/MelodyRentals#21]
Number of students: **5**
[Project link](https://github.com/users/Farida-Hamid/projects/11)
Screenshot: 
<img width="1480" alt="Screen Shot 2023-01-18 at 4 40 51 PM" src="https://user-images.githubusercontent.com/33801345/213186468-8508b4e0-89b9-424b-8dee-f5c9d2d97496.png">
<img width="1453" alt="Screen Shot 2023-01-18 at 4 41 29 PM" src="https://user-images.githubusercontent.com/33801345/213186613-a80d2f49-8bdd-4699-b340-38bf7bacb3e2.png">
<img width="1472" alt="Screen Shot 2023-01-18 at 4 41 43 PM" src="https://user-images.githubusercontent.com/33801345/213186672-2dad6d77-08b2-4d41-b50d-e96ae6a123fa.png">

**Comment by Meltrust** [comment]
Hi @Farida-Hamid,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been pointed✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] At the time of this review, these are the tasks total pointings:

x-eli 20.5
bantea 27.5
tracy 27.5
megha 23
farida 23

As you can see, @X-Elie-X has significantly less points than @Bantealem and @TracyMuso.   The rule is "no more than 5 points difference among users".  Kindly balance the points so this particular rule is met.

Tip:  Just change the points values and/or reassign some tasks and this should be ready.  👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @Farida-Hamid,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings have been balanced✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
